Repository Uninett/zino, pull requests merged in 2024-01, with the labels that each got.

#140 Remove unnecessary log dumps of state
  src/zino/state.py
  src/zino/zino.py
  tests/state_test.py
Labels: cleanup

#138 Use checkout/commit logic for all event creation/retrieval from the index
  src/zino/events.py
  src/zino/statemodels.py
  src/zino/tasks/bfdtask.py
  src/zino/tasks/juniperalarmtask.py
  src/zino/tasks/linkstatetask.py
  src/zino/tasks/reachabletask.py
  tests/api/legacy_test.py
  tests/events_test.py
  tests/state_test.py
  tests/statemodels_test.py
  tests/tasks/test_juniperalarmtask.py
  tests/tasks/test_reachabletask.py
Labels: enhancement

#143 Make event commit update event index on new and old events
  src/zino/events.py
  tests/events_test.py
Labels: bug

#122 Add Cisco support to BFD Task
  src/zino/mibdumps/CISCO-IETF-BFD-MIB.py
  src/zino/mibdumps/CISCO-SMI.py
  src/zino/statemodels.py
  src/zino/tasks/bfdtask.py
  tests/snmp_fixtures/cisco-bfd-up.snmprec
  tests/tasks/test_bfdtask.py
Labels: enhancement

#148 Initial implementation of COMMUNITY API command
  src/zino/api/legacy.py
  tests/api/legacy_test.py
Labels: enhancement, api

#145 Collect and map router IP addresses
  src/zino/mibdumps/IP-MIB.py
  src/zino/state.py
  src/zino/statemodels.py
  src/zino/tasks/__init__.py
  src/zino/tasks/addrs.py
  tests/snmp_fixtures/ip-ad-ent-addr.snmprec
  tests/snmp_test.py
  tests/tasks/test_addrs.py
Labels: enhancement

#151 Move SNMP session setup to Task initialization
  src/zino/tasks/bfdtask.py
  src/zino/tasks/juniperalarmtask.py
  src/zino/tasks/linkstatetask.py
  src/zino/tasks/reachabletask.py
  src/zino/tasks/task.py
  src/zino/tasks/vendor.py
  tests/tasks/test_reachabletask.py
  tests/tasks/test_vendor.py
Labels: cleanup

#153 Factor out get uptime
  src/zino/statemodels.py
  src/zino/tasks/linkstatetask.py
  src/zino/tasks/reachabletask.py
  src/zino/tasks/task.py
  tests/tasks/test_task.py
Labels: cleanup

#152 Add missing event commit in ADDHIST command
  src/zino/api/legacy.py
  tests/api/legacy_test.py
Labels: bug

#124 Abort other tasks if device is unreachable
  src/zino/tasks/__init__.py
  src/zino/tasks/errors.py
  src/zino/tasks/reachabletask.py
  tests/tasks/conftest.py
  tests/tasks/test_reachabletask.py
  tests/tasks/test_run_all_tasks.py
Labels: enhancement

#161 Replace overloaded `port` concept for indexing of events
  src/zino/events.py
  src/zino/statemodels.py
  src/zino/tasks/bfdtask.py
  src/zino/tasks/juniperalarmtask.py
  src/zino/tasks/linkstatetask.py
  src/zino/tasks/reachabletask.py
  tests/tasks/test_bfdtask.py
  tests/tasks/test_juniperalarmtask.py
Labels: refactor

#149 Add notification protocol
  pyproject.toml
  src/zino/api/legacy.py
  src/zino/api/notify.py
  src/zino/api/server.py
  src/zino/statemodels.py
  src/zino/zino.py
  tests/api/legacy_test.py
  tests/api/notify_test.py
  tests/api/server_test.py
  tests/statemodels_test.py
Labels: enhancement

#162 Ignore trailing garbage args on API commands
  src/zino/api/legacy.py
  tests/api/legacy_test.py
Labels: bug

#160 Add short installation/configuration section to `README.md`
  README.md
  polldevs.cf.example
Labels: documentation

#163 Fix strange bug in translation of caseids to Event objects in API commands
  src/zino/api/legacy.py
  tests/api/legacy_test.py
Labels: bug

#164 Implement line buffering in data_received()
  pyproject.toml
  src/zino/api/legacy.py
  tests/api/legacy_test.py
Labels: bug

#167 Add more text to explain what Zino is.
  README.md
Labels: documentation

#168 Add initial AUTHORS.md
  AUTHORS.md
Labels: documentation
