Repository Uninett/zino, pull requests merged in 2024-07, with the labels that each got.

#291 Add trap observer class for Juniper BGP traps
  changelog.d/291.added.md
  src/zino/trapobservers/bgp_traps.py
  src/zino/zino.py
  tests/trapobservers/bgp_traps_test.py
  tests/trapobservers/conftest.py
  tests/trapobservers/logged_traps_test.py
Labels: enhancement

#290 Resolve incoming trap varbinds properly
  changelog.d/290.fixed.md
  changelog.d/291.added.md
  src/zino/trapd.py
  src/zino/trapobservers/bgp_traps.py
  src/zino/zino.py
  tests/trapobservers/bgp_traps_test.py
  tests/trapobservers/conftest.py
  tests/trapobservers/logged_traps_test.py
Labels: bug

#249 Add generic Zino config file
  .gitignore
  README.md
  changelog.d/224.added.md
  pyproject.toml
  src/zino/api/legacy.py
  src/zino/config/__init__.py
  src/zino/config/models.py
  src/zino/events.py
  src/zino/getuptime.py
  src/zino/scheduler.py
  src/zino/state.py
  src/zino/trapd.py
  src/zino/zino.py
  tests/config_test.py
  tests/conftest.py
  tests/events_test.py
  tests/zino_test.py
  zino.toml.example
Labels: help wanted, discussion

#284 Add flapping detection algorithm to link traps
  README.md
  changelog.d/284.added.md
  src/zino/flaps.py
  src/zino/state.py
  src/zino/statemodels.py
  src/zino/tasks/task.py
  src/zino/trapobservers/link_traps.py
  src/zino/zino.py
  tests/conftest.py
  tests/flaps_test.py
  tests/trapobservers/link_traps_test.py
Labels: enhancement

#306 Fix incorrect timezone-naive datetimes
  src/zino/planned_maintenance.py
  tests/planned_maintenance_test.py
Labels: bug

#300 Add POLLINTF API command
  changelog.d/300.added.md
  src/zino/api/legacy.py
  tests/api/legacy_test.py
Labels: api

#304 Add POLLRTR API command
  changelog.d/219.added.md
  src/zino/api/legacy.py
  tests/api/legacy_test.py
Labels: api

#313 Coerce `BaseBGPRow` attribute values to expected types
  changelog.d/312.fixed.md
  pyproject.toml
  src/zino/tasks/bgpstatemonitortask.py
  tests/tasks/test_bgpstatemonitortask.py
Labels: bug

#328 Use pydantic alias for planned maintenance fields
  changelog.d/287.fixed.md
  src/zino/state.py
  src/zino/statemodels.py
  tests/planned_maintenance_test.py
Labels: bug
