Repository Uninett/zino, pull requests merged in 2024-04, with the labels that each got.

#205 Initialize state structures for new devices
  src/zino/scheduler.py
  tests/scheduler_test.py
Labels: bug

#183 Add one function to parse all weird IP formats
  src/zino/tasks/bfdtask.py
  src/zino/tasks/bgpstatemonitortask.py
  src/zino/utils.py
  tests/tasks/test_bfdtask.py
  tests/tasks/test_bgpstatemonitortask.py
  tests/utils_test.py
Labels: refactor, cleanup

#195 Fix workflow syntax and only publish test results on Uninett repo
  .github/workflows/publish-test-results.yml
  .github/workflows/tests.yml
Labels: bug, cleanup

#206 Define subindex for PortStateEvent as ifindex
  src/zino/statemodels.py
Labels: bug

#191 Add pytest-timeout to tox testenv
  tox.ini
Labels: cleanup

#181 BGP: Minimize dragging keys of sparsewalk response along
  src/zino/tasks/bgpstatemonitortask.py
Labels: cleanup

#203 Add a task that automatically deletes closed events after a certain time
  src/zino/api/notify.py
  src/zino/events.py
  src/zino/zino.py
  tests/api/notify_test.py
  tests/events_test.py
Labels: enhancement

#211 Clean up polldevs.cf.example
  polldevs.cf.example
Labels: documentation

#210 Add default authentication failure message
  src/zino/api/auth.py
Labels: bug, api
