Repository Uninett/zino, pull requests merged in 2024-08, with the labels that each got.

#335 Use pydantic alias for serialization of BGP/BFD events
  changelog.d/331.fixed.md
  src/zino/statemodels.py
  tests/api/legacy_test.py
Labels: bug, api

#344 Check actual event type and not PmType
  changelog.d/344.fixed.md
  src/zino/statemodels.py
Labels: bug

#347 Update snmpsim to newer version (>=1.0)
  pyproject.toml
  tests/conftest.py
  tox.ini
Labels: dependencies

#353 Revert using alias when dumping to state file
  src/zino/state.py
Labels: bug

#325 Improve config tests
  tests/config_test.py
Labels: cleanup

#355 Enable auto pytest-asyncio mode
  tests/api/legacy_test.py
  tests/flaps_test.py
  tests/snmp_test.py
  tests/tasks/test_addrs.py
  tests/tasks/test_bfdtask.py
  tests/tasks/test_bgpstatemonitortask.py
  tests/tasks/test_juniperalarmtask.py
  tests/tasks/test_linkstatetask.py
  tests/tasks/test_reachabletask.py
  tests/tasks/test_run_all_tasks.py
  tests/tasks/test_task.py
  tests/tasks/test_vendor.py
  tests/trapd_test.py
  tests/trapobservers/bfd_traps_test.py
  tests/trapobservers/bgp_traps_test.py
  tests/trapobservers/ignored_traps_test.py
  tests/trapobservers/link_traps_test.py
  tests/trapobservers/logged_traps_test.py
  tests/utils_test.py
  tests/zino_test.py
  tox.ini
Labels: cleanup

#322 Clean up issues with IP address parsing in several places
  src/zino/snmp.py
  src/zino/tasks/bfdtask.py
  src/zino/tasks/bgpstatemonitortask.py
  src/zino/utils.py
  tests/tasks/test_bfdtask.py
  tests/utils_test.py
Labels: cleanup

#354 Only override default config values if config file exists and is valid
  src/zino/zino.py
Labels: bug
