Repository Uninett/zino, pull requests merged in 2024-06, with the labels that each got.

#237 Exempt `raise NotImplementedError` from coverage
  pyproject.toml
Labels: coverage

#240 Fix two stupid bugs in `LinkStateTask.poll_single_interface`
  changelog.d/+poll-single-interface-ifindex.fixed.md
  changelog.d/+poll-single-interface-timeouts.fixed.md
  src/zino/tasks/linkstatetask.py
  tests/tasks/test_linkstatetask.py
Labels: bug

#231 Handle juniper devices that do not have an yellow/red alarm count
  changelog.d/231.fixed.md
  src/zino/tasks/juniperalarmtask.py
  tests/tasks/test_juniperalarmtask.py
Labels: bug

#242 Do not try to publish test results/code coverage in fork
  .github/workflows/publish-test-results.yml
Labels: coverage

#251 Add more codecov configuration to fix associating commits within PRs
  .github/workflows/publish-test-results.yml
  .github/workflows/tests.yml
Labels: coverage

#258 Fix log message on initial Juniper alarm
  changelog.d/213.added.md
  src/zino/tasks/juniperalarmtask.py
  tests/tasks/test_juniperalarmtask.py
Labels: bug

#256 Improve tests coverage of deleting expired events
  changelog.d/209.added.md
  tests/events_test.py
Labels: coverage

#260 Remove unnecessary pass keywords
  src/zino/snmp.py
Labels: cleanup

#248 Output more user-friendly error reports for `polldevs.py` parsing errors
  changelog.d/248.added.md
  src/zino/config/polldevs.py
  src/zino/scheduler.py
  tests/config/polldevs_test.py
  tests/conftest.py
  tests/scheduler_test.py
Labels: enhancement

#276 Define and use a `TypeVar` for `Event` classes
  src/zino/events.py
  src/zino/statemodels.py
Labels: cleanup
