Repository Uninett/zino, pull requests merged in 2025-09, with the labels that each got.

#433 Update README regarding usage of Zino
  README.md
Labels: documentation, nonews

#441 Format and test only code on github
  .github/workflows/format.yml
  .github/workflows/tests.yml
Labels: nonews, github_actions

#436 Move stuff from README to docs
  README.md
  changelog.d/434.added.md
  docs/configuration.rst
  docs/development.rst
  docs/howtos.rst
  docs/howtos/.gitkeep
  docs/howtos/upgrade-from-zino-1.rst
  docs/howtos/write-docs.rst
  docs/index.rst
  docs/installation.rst
  pyproject.toml
Labels: documentation

#444 Add some last minute doc system fixes
  docs/conf.py
  docs/howtos/controlling-zino-with-systemd.rst
  docs/installation.rst
Labels: documentation, nonews

#455 Fix broken netsnmpy trap receiver tests
  tests/trapd/netsnmp_backend_test.py
Labels: nonews

#478 Fix typo for rdns variable
  src/zino/tasks/bfdtask.py
Labels: nonews
